import type {
  Umbrella,
  Session,
  MenuItem,
  MenuCategory,
  Order,
  Bill,
  CreditStatus,
  PromoBanner,
  GuestJoinRequest,
} from "@/types";

// ─── Umbrellas ────────────────────────────────────────────────────────────────

export const MOCK_UMBRELLAS: Record<string, Umbrella> = {
  "A-01": {
    id: "A-01",
    number: "A-01",
    zone: "Zona Lounge",
    locationName: "Kuziini × Maya",
    active: true,
    sessionId: "sess-a01-001",
  },
  "A-02": {
    id: "A-02",
    number: "A-02",
    zone: "Zona Lounge",
    locationName: "Kuziini × Maya",
    active: true,
    sessionId: null,
  },
  "B-07": {
    id: "B-07",
    number: "B-07",
    zone: "Zona Beach",
    locationName: "Kuziini × Maya",
    active: true,
    sessionId: null,
  },
  "VIP-03": {
    id: "VIP-03",
    number: "VIP-03",
    zone: "Zona VIP Premium",
    locationName: "Kuziini × Maya",
    active: true,
    sessionId: null,
  },
};

// ─── Sessions ─────────────────────────────────────────────────────────────────

export const MOCK_SESSIONS: Record<string, Session> = {
  "sess-a01-001": {
    id: "sess-a01-001",
    umbrellaId: "A-01",
    ownerId: "user-100",
    ownerPhone: "+40700000001",
    startedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    expiresAt: null,
    closed: false,
  },
};

// ─── Login Log ───────────────────────────────────────────────────────────────

export interface LoginEntry {
  name: string;
  phone: string;
  umbrellaId: string;
  timestamp: string;
}

export const LOGIN_LOG: LoginEntry[] = [];

// ─── Bill Requests Log ───────────────────────────────────────────────────────

export interface BillRequestEntry {
  umbrellaId: string;
  paymentMethod: string;
  amount: number;
  timestamp: string;
}

export const BILL_REQUESTS_LOG: BillRequestEntry[] = [];

// ─── Order Log ───────────────────────────────────────────────────────────────

export interface OrderLogEntry {
  orderId: string;
  umbrellaId: string;
  phone: string;
  items: { name: string; quantity: number; price: number }[];
  total: number;
  timestamp: string;
}

export const ORDER_LOG: OrderLogEntry[] = [];

// ─── Menu Categories ──────────────────────────────────────────────────────────

export const MENU_CATEGORIES: MenuCategory[] = [
  { slug: "cocktails", name: "Cocktails", icon: "🍹", order: 1 },
  { slug: "shots", name: "Shots", icon: "🥃", order: 2 },
  { slug: "starters", name: "Starters", icon: "🥗", order: 3 },
  { slug: "pasta", name: "Paste & Noodles", icon: "🍝", order: 4 },
  { slug: "pizza", name: "Pizza", icon: "🍕", order: 5 },
  { slug: "sea", name: "Din Mare", icon: "🐟", order: 6 },
  { slug: "land", name: "Din Pământ", icon: "🥩", order: 7 },
  { slug: "sides", name: "Garnituri", icon: "🍟", order: 8 },
  { slug: "desserts", name: "Deserturi", icon: "🍰", order: 9 },
  { slug: "beer", name: "Bere & RTD", icon: "🍺", order: 10 },
  { slug: "energy-drinks", name: "Energy Drinks", icon: "⚡", order: 11 },
  { slug: "soft-drinks", name: "Răcoritoare", icon: "🥤", order: 12 },
  { slug: "water", name: "Apă & Cafea", icon: "💧", order: 13 },
  { slug: "wine", name: "Vinuri", icon: "🍷", order: 14 },
];

// ─── Menu Items ───────────────────────────────────────────────────────────────

export const MOCK_MENU_ITEMS: MenuItem[] = [
  // ══════════════════════════════════════════════════════════════════════════════
  // COCKTAILS
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "c-001",
    categorySlug: "cocktails",
    name: "Martini Fiero Tonic",
    description: "Martini Fiero, true tonic, orange slice · 150ml",
    price: 45,
    currency: "RON",
    available: true,
    tags: ["aperitiv", "tonic"],
  },
  {
    id: "c-002",
    categorySlug: "cocktails",
    name: "Negroni",
    description: "Martini Bitter Riserva, Martini Rubino, Bombay Sapphire, orange peel · 120ml",
    price: 55,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["bitter", "gin"],
  },
  {
    id: "c-003",
    categorySlug: "cocktails",
    name: "Moft La Maya",
    description: "Grey Goose vodka, soda water, fresh lime, fresh mint · 200ml",
    price: 55,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["vodka", "signature"],
  },
  {
    id: "c-004",
    categorySlug: "cocktails",
    name: "Margarita",
    description: "Patrón Silver, Cointreau, sugar syrup, fresh lime juice, salt · 150ml",
    price: 60,
    currency: "RON",
    available: true,
    tags: ["tequila", "lime"],
  },
  {
    id: "c-005",
    categorySlug: "cocktails",
    name: "Martinez",
    description: "Bombay Sapphire, Martini Rubino, Bols Maraschino, Angostura bitters · 120ml",
    price: 55,
    currency: "RON",
    available: true,
    tags: ["gin", "classic"],
  },
  {
    id: "c-006",
    categorySlug: "cocktails",
    name: "Bramble",
    description: "Citrum gin, Chambord, fresh lemon juice, simple syrup, blackberries · 200ml",
    price: 45,
    currency: "RON",
    available: true,
    tags: ["gin", "fructe"],
  },
  {
    id: "c-007",
    categorySlug: "cocktails",
    name: "Old Fashioned",
    description: "Woodford Reserve bourbon, sugar cube, Angostura bitters · 100ml",
    price: 75,
    currency: "RON",
    available: true,
    tags: ["bourbon", "classic"],
  },
  {
    id: "c-008",
    categorySlug: "cocktails",
    name: "Whiskey Sour",
    description: "Grants Triple Wood, fresh lemon juice, egg white, simple syrup, Angostura · 200ml",
    price: 45,
    currency: "RON",
    available: true,
    tags: ["whisky", "sour"],
  },
  {
    id: "c-009",
    categorySlug: "cocktails",
    name: "Lynchburg Lemonade",
    description: "Jack Daniel's, Bols Triple Sec, fresh lemon juice, simple syrup, lemonade · 250ml",
    price: 55,
    currency: "RON",
    available: true,
    tags: ["whisky", "lemonade"],
  },
  {
    id: "c-010",
    categorySlug: "cocktails",
    name: "Jack Daniel's Apple Tonic",
    description: "Jack Daniel's Apple, true tonic, apple garnish · 250ml",
    price: 40,
    currency: "RON",
    available: true,
    tags: ["whisky", "tonic"],
  },
  {
    id: "c-011",
    categorySlug: "cocktails",
    name: "Manhattan",
    description: "Gentleman Jack, 9 di Dante Inferno vermouth, Angostura bitters, amarena cherry · 120ml",
    price: 65,
    currency: "RON",
    available: true,
    tags: ["whisky", "classic"],
  },
  {
    id: "c-012",
    categorySlug: "cocktails",
    name: "Espresso Martini",
    description: "Grey Goose vodka, Galliano Ristretto, espresso, simple syrup, coffee beans · 150ml",
    price: 65,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["vodka", "cafea"],
  },
  {
    id: "c-013",
    categorySlug: "cocktails",
    name: "Porn Star Martini",
    description: "Grey Goose vodka, Passoa passion fruit, fresh passion fruit, Galliano vanilla · 150ml",
    price: 65,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["vodka", "fructul pasiunii"],
  },
  {
    id: "c-014",
    categorySlug: "cocktails",
    name: "French Mule",
    description: "Grey Goose vodka, fresh lime juice, true ginger, lime wheels, crushed ice · 200ml",
    price: 65,
    currency: "RON",
    available: true,
    tags: ["vodka", "ginger"],
  },
  {
    id: "c-015",
    categorySlug: "cocktails",
    name: "Mai Tai",
    description: "Mount Gay, Bols Triple Sec, orgeat syrup, fresh lime juice, mint, crushed ice · 200ml",
    price: 65,
    currency: "RON",
    available: true,
    tags: ["rom", "tropical"],
  },
  {
    id: "c-016",
    categorySlug: "cocktails",
    name: "Old Cuban",
    description: "Bacardi Spiced, St. Germain elderflower, fresh lime, simple syrup, mint · 150ml",
    price: 45,
    currency: "RON",
    available: true,
    tags: ["rom", "elderflower"],
  },
  {
    id: "c-017",
    categorySlug: "cocktails",
    name: "Daiquiri",
    description: "Bacardi Cuatro Añejo, sugar syrup, fresh lime juice, lime wheel · 150ml",
    price: 65,
    currency: "RON",
    available: true,
    tags: ["rom", "classic"],
  },
  {
    id: "c-018",
    categorySlug: "cocktails",
    name: "Mojito",
    description: "Bacardi Carta Blanca, sugar syrup, lime wedges, fresh mint, soda water, crushed ice · 300ml",
    price: 45,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["rom", "mentă"],
  },
  {
    id: "c-019",
    categorySlug: "cocktails",
    name: "Caipirinha",
    description: "Leblon Cachaça, simple syrup, lime wedges, crushed ice · 200ml",
    price: 55,
    currency: "RON",
    available: true,
    tags: ["cachaça", "lime"],
  },
  {
    id: "c-020",
    categorySlug: "cocktails",
    name: "Pisco Sour",
    description: "Macchu Pisco, simple syrup, fresh lemon juice, egg white, Angostura bitters · 200ml",
    price: 55,
    currency: "RON",
    available: true,
    tags: ["pisco", "sour"],
  },
  {
    id: "c-021",
    categorySlug: "cocktails",
    name: "Side Car",
    description: "Metaxa 7 Stars, Cointreau, fresh lemon juice, simple syrup, Peychaud's bitter · 150ml",
    price: 60,
    currency: "RON",
    available: true,
    tags: ["brandy", "classic"],
  },
  {
    id: "c-022",
    categorySlug: "cocktails",
    name: "Spanish Gin Tonic",
    description: "Bombay Sapphire, fresh herbs & fruits, grapefruit syrup, tonic water · 250ml",
    price: 45,
    currency: "RON",
    available: true,
    tags: ["gin", "tonic"],
  },
  {
    id: "c-023",
    categorySlug: "cocktails",
    name: "Blood Orange Spritz",
    description: "The Botanist Islay gin, Lilet Blanc, blood orange juice, soda, sea salt · 200ml",
    price: 45,
    currency: "RON",
    available: true,
    tags: ["gin", "spritz"],
  },
  {
    id: "c-024",
    categorySlug: "cocktails",
    name: "Tropical Gin",
    description: "Bombay Sapphire, Red Bull Tropical, mint leaves, chocolate bitter · 200ml",
    price: 45,
    currency: "RON",
    available: true,
    tags: ["gin", "tropical"],
  },
  {
    id: "c-025",
    categorySlug: "cocktails",
    name: "Hugo",
    description: "Bols Elderflower, Prosecco Martini, mint leaves, lime wedges, soda · 200ml",
    price: 55,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["prosecco", "soc"],
  },
  {
    id: "c-026",
    categorySlug: "cocktails",
    name: "Martini Vibrante",
    description: "Non-Alcoholic cocktail · Martini Vibrante",
    price: 40,
    currency: "RON",
    available: true,
    tags: ["non-alcoholic"],
  },
  {
    id: "c-027",
    categorySlug: "cocktails",
    name: "Martini Floreale",
    description: "Non-Alcoholic cocktail · Martini Floreale",
    price: 40,
    currency: "RON",
    available: true,
    tags: ["non-alcoholic"],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // SHOTS · 40ml
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "sh-001",
    categorySlug: "shots",
    name: "Jägermeister Ice Cold Shot",
    description: "35% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
    popular: true,
  },
  {
    id: "sh-002",
    categorySlug: "shots",
    name: "Jägermeister Scharf",
    description: "33% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-003",
    categorySlug: "shots",
    name: "Kamikaze Classic/Flavor",
    description: "29.5% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-004",
    categorySlug: "shots",
    name: "Godfather",
    description: "34% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-005",
    categorySlug: "shots",
    name: "Amaretto Sour",
    description: "25% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-006",
    categorySlug: "shots",
    name: "B52",
    description: "28.5% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-007",
    categorySlug: "shots",
    name: "Vișinată Bran",
    description: "30% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-008",
    categorySlug: "shots",
    name: "Afinată Bran",
    description: "30% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-009",
    categorySlug: "shots",
    name: "Nonino Grappa Tradizione",
    description: "43% ALC · 40ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-010",
    categorySlug: "shots",
    name: "Dom' Profesor Silver (Palincă Prune)",
    description: "40% ALC · 40ml",
    price: 35,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-011",
    categorySlug: "shots",
    name: "Dom' Profesor Gold (Palincă Prune)",
    description: "50% ALC · 40ml",
    price: 35,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-012",
    categorySlug: "shots",
    name: "El Jimador Blanco Agave",
    description: "35% ALC · 40ml",
    price: 35,
    currency: "RON",
    available: true,
  },
  {
    id: "sh-013",
    categorySlug: "shots",
    name: "El Jimador Reposado Agave",
    description: "40% ALC · 40ml",
    price: 35,
    currency: "RON",
    available: true,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // STARTERS
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "s-001",
    categorySlug: "starters",
    name: "Crispy Beef Rolls",
    description: "Crispy beef rolls with yakiniku sauce, kimchi cabbage, and yuzu wasabi mayonnaise · 120/40g",
    price: 75,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["vita", "asian"],
  },
  {
    id: "s-002",
    categorySlug: "starters",
    name: "Greek Salad",
    description: "The classic Greek salad · 350g",
    price: 65,
    currency: "RON",
    available: true,
    tags: ["salată", "vegetarian"],
  },
  {
    id: "s-003",
    categorySlug: "starters",
    name: "Quinoa Salad",
    description: "Quinoa salad with crunchy vegetables, yuzu dressing and shrimp · 350g",
    price: 95,
    currency: "RON",
    available: true,
    tags: ["healthy", "creveți"],
  },
  {
    id: "s-004",
    categorySlug: "starters",
    name: "Crispy Duck Salad",
    description: "Crispy duck salad with juicy pomegranate mix, green apples, celery and Peking sauce",
    price: 135,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["rață", "premium"],
  },
  {
    id: "s-005",
    categorySlug: "starters",
    name: "Crispy Eggplant",
    description: "Crispy eggplant with tempting sweet and sour sauce and crunchy onion · 150g",
    price: 50,
    currency: "RON",
    available: true,
    tags: ["vegetarian"],
  },
  {
    id: "s-006",
    categorySlug: "starters",
    name: "Tuna Carpaccio",
    description: "Tuna carpaccio with yuzu ponzu and citrus salsa · 150g",
    price: 100,
    currency: "RON",
    available: true,
    tags: ["ton", "raw"],
  },
  {
    id: "s-007",
    categorySlug: "starters",
    name: "Crispy Prawns",
    description: "Perfectly crisped prawns, coated with sweet mayonnaise and caramelized walnuts · 150g",
    price: 100,
    currency: "RON",
    available: true,
    tags: ["creveți", "nuci"],
  },
  {
    id: "s-008",
    categorySlug: "starters",
    name: "Confit Beef Tacos",
    description: "Confit beef tacos with creamy guacamole and chimichurri sauce · 150g",
    price: 80,
    currency: "RON",
    available: true,
    tags: ["vita", "tacos"],
  },
  {
    id: "s-009",
    categorySlug: "starters",
    name: "Mixed Salad Platter",
    description: "Pike roe salad, eggplant salad, hummus, roasted pepper salad · 500g",
    price: 150,
    currency: "RON",
    available: true,
    tags: ["platou", "sharing"],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // PASTA & NOODLES
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "p-001",
    categorySlug: "pasta",
    name: "Spaghetti Carbonara",
    description: "Classic spaghetti carbonara, featuring creamy sauce, crispy bacon and grated Parmesan · 300g",
    price: 55,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["paste", "clasic"],
  },
  {
    id: "p-002",
    categorySlug: "pasta",
    name: "Bulgogi Beef Noodles",
    description: "Savory bulgogi beef stir-fry noodles enhanced with Hong Kong sauce · 300g",
    price: 95,
    currency: "RON",
    available: true,
    tags: ["noodles", "asian"],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // PIZZA · all 400g
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "pz-001",
    categorySlug: "pizza",
    name: "Pizza Tartufata",
    description: "Cu trufe · 400g",
    price: 75,
    currency: "RON",
    available: true,
    popular: true,
  },
  {
    id: "pz-002",
    categorySlug: "pizza",
    name: "Pizza Margherita",
    description: "Clasica italiană · 400g",
    price: 75,
    currency: "RON",
    available: true,
  },
  {
    id: "pz-003",
    categorySlug: "pizza",
    name: "Pizza Diavola",
    description: "Picantă · 400g",
    price: 75,
    currency: "RON",
    available: true,
  },
  {
    id: "pz-004",
    categorySlug: "pizza",
    name: "Pizza Prosciutto e Funghi",
    description: "Prosciutto și ciuperci · 400g",
    price: 75,
    currency: "RON",
    available: true,
  },
  {
    id: "pz-005",
    categorySlug: "pizza",
    name: "Pizza Quattro Formaggi",
    description: "Patru brânzeturi · 400g",
    price: 75,
    currency: "RON",
    available: true,
  },
  {
    id: "pz-006",
    categorySlug: "pizza",
    name: "Pizza Quattro Stagioni",
    description: "Patru anotimpuri · 400g",
    price: 75,
    currency: "RON",
    available: true,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // DIN MARE
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "sea-001",
    categorySlug: "sea",
    name: "Salmon Teriyaki",
    description: "Hoba leaf-infused salmon teriyaki, grilled to perfection · 250g",
    price: 100,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["somon", "teriyaki"],
  },
  {
    id: "sea-002",
    categorySlug: "sea",
    name: "Grilled Squid",
    description: "Grilled squid accompanied by fresh vegetable salsa and creamy feta cheese · 350g",
    price: 135,
    currency: "RON",
    available: true,
    tags: ["calamar", "grătar"],
  },
  {
    id: "sea-003",
    categorySlug: "sea",
    name: "Sea Bass Fillet",
    description: "Sea bass fillet with yuzu and ginger butter sauce, served with sauteed baby spinach · 140/50/70g",
    price: 125,
    currency: "RON",
    available: true,
    tags: ["biban", "premium"],
  },
  {
    id: "sea-004",
    categorySlug: "sea",
    name: "Glazed Octopus",
    description: "Octopus glazed with aka miso, sweet potato puree with yuzu and seaweed chips · 150/100g",
    price: 150,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["caracatiță", "miso"],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // DIN PĂMÂNT
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "l-001",
    categorySlug: "land",
    name: "Turkey Schnitzel",
    description: "Turkey schnitzel, crispy and delightful · 250g",
    price: 85,
    currency: "RON",
    available: true,
    tags: ["curcan", "schnitzel"],
  },
  {
    id: "l-002",
    categorySlug: "land",
    name: "Grilled Pork Chop",
    description: "Grilled pork chop, served with yakiniku glaze and sauteed pak choi · 220/150g",
    price: 85,
    currency: "RON",
    available: true,
    tags: ["porc", "grătar"],
  },
  {
    id: "l-003",
    categorySlug: "land",
    name: "Grilled Beef Entrecote",
    description: "Grilled beef entrecote paired with flavourful chimichurri sauce · 300g",
    price: 245,
    currency: "RON",
    available: true,
    tags: ["vita", "premium"],
  },
  {
    id: "l-004",
    categorySlug: "land",
    name: "Chicken Skewers",
    description: "Chicken skewers marinated in yuzu kosho, with crunchy salad of daikon, carrot and dashi dressing · 220/70g",
    price: 95,
    currency: "RON",
    available: true,
    tags: ["pui", "skewers"],
  },
  {
    id: "l-005",
    categorySlug: "land",
    name: "Miso Chicken",
    description: "Tender chicken infused with miso, citrus zest and chimichurri · 350g",
    price: 95,
    currency: "RON",
    available: true,
    tags: ["pui", "miso"],
  },
  {
    id: "l-006",
    categorySlug: "land",
    name: "Beef Stir-Fry",
    description: "Crispy beef prepared in the wok, with hot & spicy sauce and vegetables",
    price: 85,
    currency: "RON",
    available: true,
    tags: ["vita", "wok"],
  },
  {
    id: "l-007",
    categorySlug: "land",
    name: "Black Angus Burger",
    description: "Smach black Angus burger with cheddar, special kimchi sauce and golden fries dusted with Parmesan and garlic · 250g",
    price: 100,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["burger", "angus"],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // GARNITURI
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "side-001",
    categorySlug: "sides",
    name: "French Fries",
    description: "Cartofi prăjiți clasici · 250g",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "side-002",
    categorySlug: "sides",
    name: "French Fries with Cheese",
    description: "Cartofi prăjiți cu brânză · 250g",
    price: 35,
    currency: "RON",
    available: true,
    popular: true,
  },
  {
    id: "side-003",
    categorySlug: "sides",
    name: "Mashed Potatoes",
    description: "Piure de cartofi · 250g",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "side-004",
    categorySlug: "sides",
    name: "Mashed Potatoes with Truffles",
    description: "Piure cu trufe · 250g",
    price: 35,
    currency: "RON",
    available: true,
  },
  {
    id: "side-005",
    categorySlug: "sides",
    name: "Fried Rice with Kimchi",
    description: "Fried rice with kimchi sauce, peas and egg · 300g",
    price: 35,
    currency: "RON",
    available: true,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // DESERTURI
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "d-001",
    categorySlug: "desserts",
    name: "Trio Chocolate Cake",
    description: "Trio chocolate cake, served with delicious vanilla ice cream · 160g",
    price: 65,
    currency: "RON",
    available: true,
    popular: true,
  },
  {
    id: "d-002",
    categorySlug: "desserts",
    name: "Pavlova",
    description: "Pavlova with mascarpone, crowded with abundance of fresh forest fruits · 140g",
    price: 65,
    currency: "RON",
    available: true,
  },
  {
    id: "d-003",
    categorySlug: "desserts",
    name: "Tiramisu",
    description: "Rețetă clasică · 120g",
    price: 65,
    currency: "RON",
    available: true,
  },
  {
    id: "d-004",
    categorySlug: "desserts",
    name: "Ice Cream",
    description: "3 scoops (ask waiter for favourite flavour)",
    price: 65,
    currency: "RON",
    available: true,
  },
  {
    id: "d-005",
    categorySlug: "desserts",
    name: "Fresh Fruit Platter",
    description: "Fresh fruit platter (perfect for 2) · 1kg",
    price: 135,
    currency: "RON",
    available: true,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // BERE & RTD
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "beer-001",
    categorySlug: "beer",
    name: "Noam Lager",
    description: "5.2% ALC · 330ml",
    price: 30,
    currency: "RON",
    available: true,
    popular: true,
  },
  {
    id: "beer-002",
    categorySlug: "beer",
    name: "Heineken",
    description: "5% ALC · 330ml",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "beer-003",
    categorySlug: "beer",
    name: "Budweiser Budvar Pilsner",
    description: "5% ALC · 330ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "beer-004",
    categorySlug: "beer",
    name: "Bacardi Breezer",
    description: "Lime / Watermelon / Orange · 4% ALC · 375ml",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "beer-005",
    categorySlug: "beer",
    name: "Heineken 0.0",
    description: "Non-Alcoholic · 330ml",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "beer-006",
    categorySlug: "beer",
    name: "Birra Moretti 0.0",
    description: "Non-Alcoholic · 330ml",
    price: 25,
    currency: "RON",
    available: true,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // ENERGY DRINKS · 250ml
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "ed-001",
    categorySlug: "energy-drinks",
    name: "Red Bull Original",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "ed-002",
    categorySlug: "energy-drinks",
    name: "Red Bull Sugar Free",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "ed-003",
    categorySlug: "energy-drinks",
    name: "Red Bull Tropical",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
    popular: true,
  },
  {
    id: "ed-004",
    categorySlug: "energy-drinks",
    name: "Red Bull Watermelon",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "ed-005",
    categorySlug: "energy-drinks",
    name: "Red Bull Blueberry",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "ed-006",
    categorySlug: "energy-drinks",
    name: "Red Bull Forest Fruit Sugar Free",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "ed-007",
    categorySlug: "energy-drinks",
    name: "Burn Original",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "ed-008",
    categorySlug: "energy-drinks",
    name: "Fi-Ga Juice Fiori di Guarana",
    description: "250ml",
    price: 25,
    currency: "RON",
    available: true,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // RĂCORITOARE & SOFT DRINKS
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "sd-001",
    categorySlug: "soft-drinks",
    name: "Natural Lemonade",
    description: "Fresh lemon & orange juice, sugar syrup, water · 350ml",
    price: 30,
    currency: "RON",
    available: true,
    popular: true,
  },
  {
    id: "sd-002",
    categorySlug: "soft-drinks",
    name: "Coca-Cola Original",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-003",
    categorySlug: "soft-drinks",
    name: "Coca-Cola Zero Sugar",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-004",
    categorySlug: "soft-drinks",
    name: "Fanta Orange",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-005",
    categorySlug: "soft-drinks",
    name: "Sprite",
    description: "250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-006",
    categorySlug: "soft-drinks",
    name: "Schweppes Tonic",
    description: "Tonic / Pink / Bitter Lemon / Mandarin · 250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-007",
    categorySlug: "soft-drinks",
    name: "Fuze Tea",
    description: "Lemon / Peach Hibiscus · 250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-008",
    categorySlug: "soft-drinks",
    name: "Cappy Nectar Juice",
    description: "Orange / Peach / Pear / Red Orange / Sour Cherry · 250ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-009",
    categorySlug: "soft-drinks",
    name: "Arizona Ice Tea",
    description: "500ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-010",
    categorySlug: "soft-drinks",
    name: "True Social Tonic",
    description: "Tonic / Happiness Ginger / Life Pink Soda · 200ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-011",
    categorySlug: "soft-drinks",
    name: "Archibald Apa Tonica Original",
    description: "200ml",
    price: 30,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-012",
    categorySlug: "soft-drinks",
    name: "Granini Fruit Juices",
    description: "1L",
    price: 55,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-013",
    categorySlug: "soft-drinks",
    name: "Ocean Spray Cranberry Juice",
    description: "1L",
    price: 55,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-014",
    categorySlug: "soft-drinks",
    name: "Coconaut Pure Young Coconut Water",
    description: "320ml",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-015",
    categorySlug: "soft-drinks",
    name: "Coconaut Sparkling Young Coconut Water",
    description: "320ml",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-016",
    categorySlug: "soft-drinks",
    name: "Coconaut Pineapple Juice Coconut Water",
    description: "320ml",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "sd-017",
    categorySlug: "soft-drinks",
    name: "Coconaut Watermelon Juice Coconut Water",
    description: "320ml",
    price: 25,
    currency: "RON",
    available: true,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // APĂ & CAFEA
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: "w-001",
    categorySlug: "water",
    name: "Evian Still Natural Mineral Water",
    description: "330ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "w-002",
    categorySlug: "water",
    name: "Evian Sparkling Mineral Water",
    description: "330ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "w-003",
    categorySlug: "water",
    name: "Badoit Rouge Sparkling Mineral Water",
    description: "330ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "w-004",
    categorySlug: "water",
    name: "Dorna Still/Sparkling Mineral Water",
    description: "330ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "w-005",
    categorySlug: "water",
    name: "Espresso",
    description: "30ml",
    price: 20,
    currency: "RON",
    available: true,
  },
  {
    id: "w-006",
    categorySlug: "water",
    name: "Caffè Latte",
    description: "250ml",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "w-007",
    categorySlug: "water",
    name: "Cappuccino",
    description: "180ml",
    price: 25,
    currency: "RON",
    available: true,
  },
  {
    id: "w-008",
    categorySlug: "water",
    name: "Revolution Hot Tea",
    description: "300ml",
    price: 20,
    currency: "RON",
    available: true,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // VINURI
  // ══════════════════════════════════════════════════════════════════════════════

  // ── Wine by the Glass ──
  {
    id: "wine-001",
    categorySlug: "wine",
    name: "Tarlà 101 Cupaj Alb (pahar)",
    description: "Sauvignon Blanc, Chardonnay · 150ml",
    price: 60,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-002",
    categorySlug: "wine",
    name: "Tarlà 101 Rosé (pahar)",
    description: "Merlot, Cabernet Sauvignon · 150ml",
    price: 60,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-003",
    categorySlug: "wine",
    name: "Tarlà 101 Roșu (pahar)",
    description: "Merlot, Feteasca Neagră, Cabernet Sauvignon · 150ml",
    price: 60,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-004",
    categorySlug: "wine",
    name: "Martini Prosecco (pahar)",
    description: "Prosecco Dry · 100ml",
    price: 55,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-005",
    categorySlug: "wine",
    name: "Martini Asti (pahar)",
    description: "Medium Sweet · 100ml",
    price: 55,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-006",
    categorySlug: "wine",
    name: "Martini Rosé (pahar)",
    description: "Medium Dry · 100ml",
    price: 55,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-007",
    categorySlug: "wine",
    name: "Martini Sparkling Brut (pahar)",
    description: "Brut · 100ml",
    price: 55,
    currency: "RON",
    available: true,
  },

  // ── Sparkling & Champagne ──
  {
    id: "wine-010",
    categorySlug: "wine",
    name: "Martini Prosecco Dry",
    description: "750ml",
    price: 375,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-011",
    categorySlug: "wine",
    name: "Martini Asti Medium Sweet",
    description: "750ml",
    price: 375,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-012",
    categorySlug: "wine",
    name: "Martini Rosé Medium Dry",
    description: "750ml",
    price: 375,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-013",
    categorySlug: "wine",
    name: "Martini Sparkling Brut",
    description: "750ml",
    price: 375,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-014",
    categorySlug: "wine",
    name: "Laurent-Perrier La Cuvée Brut",
    description: "Champagne · 750ml",
    price: 650,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["champagne", "premium"],
  },
  {
    id: "wine-015",
    categorySlug: "wine",
    name: "Laurent-Perrier Harmony Demisec",
    description: "Champagne · 750ml",
    price: 650,
    currency: "RON",
    available: true,
    tags: ["champagne"],
  },
  {
    id: "wine-016",
    categorySlug: "wine",
    name: "Laurent-Perrier Cuvée Rosé",
    description: "Champagne Rosé · 750ml",
    price: 950,
    currency: "RON",
    available: true,
    tags: ["champagne", "rosé"],
  },
  {
    id: "wine-017",
    categorySlug: "wine",
    name: "Dom Pérignon Brut",
    description: "Champagne · 750ml",
    price: 3700,
    currency: "RON",
    available: true,
    tags: ["champagne", "luxury"],
  },
  {
    id: "wine-018",
    categorySlug: "wine",
    name: "Armand de Brignac Brut Gold",
    description: "Champagne · 750ml",
    price: 3850,
    currency: "RON",
    available: true,
    tags: ["champagne", "luxury"],
  },
  {
    id: "wine-019",
    categorySlug: "wine",
    name: "Armand de Brignac Rosé",
    description: "Champagne Rosé · 750ml",
    price: 5600,
    currency: "RON",
    available: true,
    tags: ["champagne", "luxury"],
  },

  // ── White Wines ──
  {
    id: "wine-020",
    categorySlug: "wine",
    name: "Tarlà 101 Cupaj Alb",
    description: "White Blend · România · 750ml",
    price: 300,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-021",
    categorySlug: "wine",
    name: "Tarlà 201 Chardonnay Barrique",
    description: "Chardonnay 2021 · România · 750ml",
    price: 375,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-022",
    categorySlug: "wine",
    name: "Tarlà Maya Edition Chardonnay",
    description: "Dealu Mare · România · 1.5L Magnum",
    price: 650,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["magnum", "exclusive"],
  },
  {
    id: "wine-023",
    categorySlug: "wine",
    name: "Lamblin & Fils Chardonnay Pays d'Oc",
    description: "Chardonnay · France · 750ml",
    price: 275,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-024",
    categorySlug: "wine",
    name: "Roux Père & Fils Les Cotilles",
    description: "Chardonnay 2023 · Bourgogne · 750ml",
    price: 275,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-025",
    categorySlug: "wine",
    name: "Lamblin & Fils Chablis Fût de Chêne",
    description: "Chardonnay · Chablis · 750ml",
    price: 450,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-026",
    categorySlug: "wine",
    name: "Maison de Ladoucette Pouilly-Fumé",
    description: "Sauvignon Blanc · Loire · 750ml",
    price: 450,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-027",
    categorySlug: "wine",
    name: "Regnard Chablis Grand Regnard",
    description: "Chardonnay · Chablis · 750ml",
    price: 550,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-028",
    categorySlug: "wine",
    name: "Stefano Farina Gavi del Comune di Gavi",
    description: "Cortese · Piemonte · 750ml",
    price: 325,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-029",
    categorySlug: "wine",
    name: "Villa Raiano Greco di Tufo DOCG",
    description: "Greco 2022 · Italia · 750ml",
    price: 325,
    currency: "RON",
    available: true,
  },

  // ── Rosé Wines ──
  {
    id: "wine-030",
    categorySlug: "wine",
    name: "Tarlà 101 Rosé",
    description: "Merlot, Cabernet Sauvignon · România · 750ml",
    price: 300,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-031",
    categorySlug: "wine",
    name: "Tarlà Maya Edition Rosé",
    description: "Syrah, Grenache, Cinsault · Côtes de Provence · 1.5L Magnum",
    price: 650,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["magnum", "exclusive"],
  },
  {
    id: "wine-032",
    categorySlug: "wine",
    name: "Cantine San Giorgio Negroamaro Rosato",
    description: "Negroamaro · Salento, Puglia · 750ml",
    price: 275,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-033",
    categorySlug: "wine",
    name: "Mouton Cadet Rosé",
    description: "Baron Philippe de Rothschild · Bordeaux · 750ml",
    price: 325,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-034",
    categorySlug: "wine",
    name: "Whispering Angel Rosé",
    description: "Château d'Esclans · Côtes de Provence · 750ml",
    price: 375,
    currency: "RON",
    available: true,
    popular: true,
    tags: ["rosé", "provence"],
  },
  {
    id: "wine-035",
    categorySlug: "wine",
    name: "Rock Angel Rosé",
    description: "Château d'Esclans · Côtes de Provence · 750ml",
    price: 450,
    currency: "RON",
    available: true,
    tags: ["rosé", "provence"],
  },
  {
    id: "wine-036",
    categorySlug: "wine",
    name: "Château d'Esclans Rosé",
    description: "Grenache, Rolle · Côtes de Provence · 750ml",
    price: 550,
    currency: "RON",
    available: true,
    tags: ["rosé", "premium"],
  },
  {
    id: "wine-037",
    categorySlug: "wine",
    name: "Les Clans Rosé",
    description: "Château d'Esclans · Côtes de Provence · 750ml",
    price: 650,
    currency: "RON",
    available: true,
    tags: ["rosé", "premium"],
  },
  {
    id: "wine-038",
    categorySlug: "wine",
    name: "Garrus Rosé",
    description: "Château d'Esclans · Côtes de Provence · 750ml",
    price: 1100,
    currency: "RON",
    available: true,
    tags: ["rosé", "luxury"],
  },

  // ── Red Wines ──
  {
    id: "wine-040",
    categorySlug: "wine",
    name: "Tarlà 101 Roșu",
    description: "Merlot, Feteasca Neagră, Cabernet Sauvignon · Ceptura · 750ml",
    price: 300,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-041",
    categorySlug: "wine",
    name: "Tarlà 201 Roșu",
    description: "Cabernet Sauvignon, Syrah, Merlot · Dealu Mare · 750ml",
    price: 375,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-042",
    categorySlug: "wine",
    name: "Mouton Cadet Cuvée Héritage Rouge",
    description: "Merlot, Cabernet Sauvignon · Bordeaux · 750ml",
    price: 325,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-043",
    categorySlug: "wine",
    name: "Château Ferran Saint Pierre",
    description: "Merlot, Cabernet Sauvignon, Cabernet Franc · Bordeaux Supérieur · 750ml",
    price: 325,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-044",
    categorySlug: "wine",
    name: "Stefano Farina Chianti Classico Riserva",
    description: "Sangiovese · Toscana · 750ml",
    price: 325,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-045",
    categorySlug: "wine",
    name: "Chivite Finca de Villatuerta",
    description: "Tempranillo, Merlot, Garnacha, Syrah · Navarra · 750ml",
    price: 325,
    currency: "RON",
    available: true,
  },
  {
    id: "wine-046",
    categorySlug: "wine",
    name: "Tenuta Valleselle Amarone della Valpolicella",
    description: "Corvina, Corvinone, Rondinella · Veneto · 750ml",
    price: 675,
    currency: "RON",
    available: true,
    tags: ["premium", "amarone"],
  },
];

// ─── Mock Orders ──────────────────────────────────────────────────────────────

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-001",
    umbrellaId: "A-01",
    deliveryUmbrellaId: "A-01",
    billingUmbrellaId: "A-01",
    sessionId: "sess-a01-001",
    guestPhone: "+40700000001",
    role: "owner",
    items: [
      {
        menuItemId: "c-002",
        name: "Negroni",
        price: 55,
        quantity: 2,
      },
      {
        menuItemId: "s-001",
        name: "Crispy Beef Rolls",
        price: 75,
        quantity: 1,
      },
    ],
    subtotal: 185,
    total: 185,
    status: "delivered",
    visibility: "own",
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    ownerApprovalRequired: false,
    ownerApproved: null,
  },
];

// ─── Mock Bill ────────────────────────────────────────────────────────────────

export const MOCK_BILL: Bill = {
  id: "bill-a01-001",
  umbrellaId: "A-01",
  sessionId: "sess-a01-001",
  orders: MOCK_ORDERS,
  subtotal: 185,
  total: 185,
  status: "open",
};

// ─── Credit Status ────────────────────────────────────────────────────────────

export const MOCK_CREDIT_STATUS: CreditStatus = {
  eligible: true,
  roomNumber: "304",
  guestName: "Andrei Popescu",
  limitTotal: 1500,
  limitUsed: 320,
  limitAvailable: 1180,
  currency: "RON",
};

// ─── Promo Banners ────────────────────────────────────────────────────────────

export const Maya_BANNERS: PromoBanner[] = [
  {
    id: "Maya-1",
    title: "Happy Hour",
    subtitle: "Cocktailuri 2×1 · 15:00–17:00",
    emoji: "🍹",
    color: "from-coral-400 to-coral-600",
    order: 0,
  },
  {
    id: "Maya-2",
    title: "Maya Signature",
    subtitle: "Moft La Maya · Grey Goose & Lime · 55 RON",
    emoji: "✨",
    color: "from-ocean-400 to-ocean-600",
    order: 1,
  },
  {
    id: "Maya-3",
    title: "Weekend Special",
    subtitle: "Glazed Octopus + Prosecco la 195 RON",
    emoji: "🐙",
    color: "from-sand-400 to-sand-600",
    order: 2,
  },
];

export const KUZIINI_BANNERS: PromoBanner[] = [
  {
    id: "kuziini-1",
    title: "Kuziini Fresh",
    subtitle: "Smoothie-uri naturale din fructe proaspete",
    emoji: "🥤",
    color: "from-green-400 to-green-600",
    order: 0,
  },
  {
    id: "kuziini-2",
    title: "Kuziini Brunch",
    subtitle: "Brunch zilnic · 10:00–13:00",
    emoji: "🥞",
    color: "from-amber-400 to-amber-600",
    order: 1,
  },
  {
    id: "kuziini-3",
    title: "Concept Store",
    subtitle: "Descoperă colecția de vară Kuziini",
    emoji: "🛍️",
    color: "from-purple-400 to-purple-600",
    order: 2,
  },
];

// Keep backward compat reference
export const PROMO_BANNERS: PromoBanner[] = Maya_BANNERS;

// ─── Landing Page Galleries ──────────────────────────────────────────────────

export type GalleryAspect = "square" | "portrait" | "landscape";

export interface GalleryConfig {
  slots: number; // 1, 2, 3, 4, or 6
  aspect: GalleryAspect;
  images: GalleryImage[];
}

export interface GalleryImage {
  id: string;
  url: string; // base64 or external URL
  order: number;
}

export const Maya_GALLERY: GalleryConfig = {
  slots: 3,
  aspect: "square",
  images: [    {
      id: "maya-1",
      url: "/1.jpg",
      order: 0
    },
    {
      id: "maya-3",
      url: "/3.jpg",
      order: 1
    },
    {
      id: "maya-4",
      url: "/4.jpg",
      order: 2
    },
    {
      id: "maya-5",
      url: "/5.jpg",
      order: 3
    },
    {
      id: "maya-11",
      url: "/11.jpg",
      order: 4
    },
    {
      id: "maya-12",
      url: "/12.jpeg",
      order: 5
    },
    {
      id: "maya-13",
      url: "/13.jpeg",
      order: 6
    },
    {
      id: "maya-14",
      url: "/14.jpeg",
      order: 7
    },
    {
      id: "maya-15",
      url: "/15.jpeg",
      order: 8
    }]
};

export const KUZIINI_GALLERY: GalleryConfig = {
  slots: 3,
  aspect: "square",
  images: []
};

// ─── Photo Library ──────────────────────────────────────────────────────────
export interface LibraryPhoto {
  id: string;
  url: string;
  addedAt: string;
}

export const Maya_LIBRARY: LibraryPhoto[] = [];

export const KUZIINI_LIBRARY: LibraryPhoto[] = [];

// ─── Mock Guest Requests ──────────────────────────────────────────────────────

export const MOCK_GUEST_REQUESTS: GuestJoinRequest[] = [];


